name: Deploy PROD

on:
  [workflow_dispatch]
  
jobs:
  DeployClient:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cmlg-frontend
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - run: npm install
      - run: CI=false npm run build
  
      - uses: 'google-github-actions/auth@v0'
        with:
          
          # Credentials stored inside WDCC organisation secrets
          credentials_json: '${{ secrets.CMLG_GCP_DEPLOYMENT_SA_CREDENTIALS }}'

      - uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
        
          # Build path (path is excluded due to parent: false flag)
          path: './cmlg-frontend/build'
          parent: false
          
          # Bucket to add contents into
          destination: 'cmlg-prod.wdcc.co.nz'
